version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Build started
      - export CODEARTIFACT_TOKEN=`aws --region eu-west-1 codeartifact get-authorization-token --domain development --domain-owner 889199313043 --query authorizationToken --output text`
  build:
    commands:
      - mvn -s settings.xml clean package deploy
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/iplib-1.0-SNAPSHOT.jar
  name: photo-wasabi-$(date +%Y%m%d.%H%M%s).zip
