version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Build started
      - mvn clean test
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/iplib-1.0-SNAPSHOT.jar
  name: photo-wasabi-$(date +%Y%m%d.%H%M%s).zip
