version: 0.2

env:
  variables:
    STAMP: "1.0-"`date +%Y%m%d.%H%M%S`
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Build started
  build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws --region eu-west-1 codeartifact get-authorization-token --domain development --domain-owner 889199313043 --query authorizationToken --output text`
      - mvn --no-transfer-progress versions:set -DnewVersion=$STAMP
      - mvn --no-transfer-progress -s settings.xml clean package deploy
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/iplib-$STAMP.jar
  name: iplib-$STAMP.jar
